### ISSUE TITLE
Image elements do not have [alt] attributes

### ISSUE THREAD

**Issue by mwhite192** [mwhite192/GoMikeDesigns#10]
## Before
_<sub>Note: Info provided is prior to action taken to increase **SEO**._ </sub>

**Issue**: Image elements do not have `alt` attributes
**Category**: _Accessiblity and **SEO**_
**Explanation**: Informative elements should aim for short, descriptive alternate text. Decorative elements can be ignored with an empty `alt` attribute
**Code Sample**: 
https://github.com/mwhite192/GoMikeDesigns/blob/39b31dcd7fd22a0b4db7e3b7adf2b30521f4a85b/page2.html#L38

**Comment by mwhite192** [comment]
## After
_<sub>Note: Info provided occurs after action is taken to increase **SEO**._ </sub>

**Action Taken:** Add `alt` attribute to `<img>` tag embedded in an `<a>` tag.
**Code  Sample:**
https://github.com/mwhite192/GoMikeDesigns/blob/3d8b176e0ff924f564819b95ac73c605cd23e48d/index.html#L40

**Comment by AccessiT3ch** [comment]
@mwhite192 - I don't see an image in the code example you gave :)

**Comment by mwhite192** [comment]
@AccessiT3ch - this was the snippet of code that came up in the Lighhouse report for this particular issue. I wll do some more research and if I can't get to the bottom of the matter.  I will be sure to keep you posted.

**Comment by mwhite192** [comment]
@AccessiT3ch - I copied the wrong ling of code :\
