### ISSUE TITLE
Links do not have a discernible name

### ISSUE THREAD

**Issue by mwhite192** [mwhite192/GoMikeDesigns#2]
## Before
_<sub>Note: Info provided is prior to action taken to increase **SEO**._ </sub>

**Issue**: Links do not have a discernible name
**Category**: _Accessiblity_
**Explanation**: Link text (and alternate text for images, when used as links) that is discernible, unique, and focusable improves the navigation experience for screen reader users
**Code Sample**: 
https://github.com/mwhite192/GoMikeDesigns/blob/744cd0db55f0475ee1880a9772b0ab45f90277bd/index.html#L230-L245
https://github.com/mwhite192/GoMikeDesigns/blob/39b31dcd7fd22a0b4db7e3b7adf2b30521f4a85b/page2.html#L38
https://github.com/mwhite192/GoMikeDesigns/blob/39b31dcd7fd22a0b4db7e3b7adf2b30521f4a85b/page2.html#L137-L153

**Comment by mwhite192** [comment]
## After
_<sub>Note: Info provided occurs after action is taken to increase **SEO**._ </sub>

**Action Taken:** Added `aria-label` attribute to `<a>` elements for lines 137-153 38, and 121; added `alt` attribute to `<img>` element on line 38; applied same action for index.html
**Code Sample:**
https://github.com/mwhite192/GoMikeDesigns/blob/82e9fae5eb9aa0cae47c44cdddccf78d49ca5996/index.html#L230-L245
https://github.com/mwhite192/GoMikeDesigns/blob/3d8b176e0ff924f564819b95ac73c605cd23e48d/page2.html#L38
https://github.com/mwhite192/GoMikeDesigns/blob/cdc5b6f48a787efa7b054071253242306642ae16/page2.html#L137-L153
https://github.com/mwhite192/GoMikeDesigns/blob/3d8b176e0ff924f564819b95ac73c605cd23e48d/page2.html#L121

**Comment by AccessiT3ch** [comment]
@mwhite192 - good job here, I think the `aria-label` was the right way to go here considering the innerHTML of those links were icons / images. If there are cases where the anchor tag has actual text innerHTML then the `title` attribute will be more appropriate (since it should match the innerHTML text).
