### ISSUE TITLE
Background and foreground colors do not have a sufficient contrast ratio

### ISSUE THREAD

**Issue by mwhite192** [mwhite192/GoMikeDesigns#3]
## Before
_<sub>Note: Info provided is prior to action taken to increase **SEO**._ </sub>

**Issue**: Background and foreground colors do not have a sufficient contrast ratio
**Category**: _Accessiblity_
**Explanation**: Low-contrast text is difficult or impossible for many users to read
**Code Sample**: 
https://github.com/mwhite192/GoMikeDesigns/blob/855a118ddc1fdd17d630a0be6528121a2effef90/index.html#L218
https://github.com/mwhite192/GoMikeDesigns/blob/855a118ddc1fdd17d630a0be6528121a2effef90/index.html#L254-L257
https://github.com/mwhite192/GoMikeDesigns/blob/855a118ddc1fdd17d630a0be6528121a2effef90/index.html#L263-L271
https://github.com/mwhite192/GoMikeDesigns/blob/855a118ddc1fdd17d630a0be6528121a2effef90/index.html#L277-L285
https://github.com/mwhite192/GoMikeDesigns/blob/39b31dcd7fd22a0b4db7e3b7adf2b30521f4a85b/page2.html#L106-L108
https://github.com/mwhite192/GoMikeDesigns/blob/39b31dcd7fd22a0b4db7e3b7adf2b30521f4a85b/page2.html#L113
https://github.com/mwhite192/GoMikeDesigns/blob/39b31dcd7fd22a0b4db7e3b7adf2b30521f4a85b/page2.html#L78

**Comment by mwhite192** [comment]
## After
_<sub>Note: Info provided occurs after action is taken to increase **SEO**._ </sub>

**Action Taken:** Removed links from the footer as links are not "working"; added the below snippets of CSS code 
**Code  Sample:**
https://github.com/mwhite192/GoMikeDesigns/blob/c773564ea79bb9be6b751b0d8cd322d13bc028f7/style.css#L783-L785
https://github.com/mwhite192/GoMikeDesigns/blob/c773564ea79bb9be6b751b0d8cd322d13bc028f7/style.css#L787-L790
https://github.com/mwhite192/GoMikeDesigns/blob/5c5882a127a750c9fdb45cb21731eef0a0443dcf/style.css#L805-L807

**Comment by AccessiT3ch** [comment]
@mwhite192 - you can check color contrasts on [Adobe's free color tool](https://color.adobe.com/create/color-wheel) in the [accessibility tools tab](https://color.adobe.com/create/color-contrast-analyzer), I like this one because it will suggest new colors with sufficient ratios!
