### ISSUE TITLE
Serve images in next-gen formats

### ISSUE THREAD

**Issue by mwhite192** [mwhite192/GoMikeDesigns#8]
## Before
_<sub>Note: Info provided is prior to action taken to increase **SEO**._ </sub>

**Issue**: Serve images in next-gen formats
**Category**: _Performance_
**Explanation**: Image formats like WebP and AVIF often provide better compression than PNG or JPEG, which means faster downloads and less data consumption
**Code Sample**:  
https://github.com/mwhite192/GoMikeDesigns/blob/39b31dcd7fd22a0b4db7e3b7adf2b30521f4a85b/index.html#L69
https://github.com/mwhite192/GoMikeDesigns/blob/39b31dcd7fd22a0b4db7e3b7adf2b30521f4a85b/index.html#L162
https://github.com/mwhite192/GoMikeDesigns/blob/39b31dcd7fd22a0b4db7e3b7adf2b30521f4a85b/index.html#L171
https://github.com/mwhite192/GoMikeDesigns/blob/39b31dcd7fd22a0b4db7e3b7adf2b30521f4a85b/index.html#L182
https://github.com/mwhite192/GoMikeDesigns/blob/39b31dcd7fd22a0b4db7e3b7adf2b30521f4a85b/index.html#L191

**Comment by mwhite192** [comment]
## After
_<sub>Note: Info provided occurs after action is taken to increase **SEO**._ </sub>

**Action Taken:**  Renamed each image to reflect contents of image; compressed each image file into a .webp file; removed all previous gen image files; relinked each image with new, next gen image
**Code  Sample:**
https://github.com/mwhite192/GoMikeDesigns/blob/3d8b176e0ff924f564819b95ac73c605cd23e48d/index.html#L8
https://github.com/mwhite192/GoMikeDesigns/blob/96913e775f229c0c7c78c2b453b91e23a5df0078/page2.html#L38
https://github.com/mwhite192/GoMikeDesigns/blob/8808521a8a76216cd4890aec288775b8f95d2f3e/index.html#L40
https://github.com/mwhite192/GoMikeDesigns/blob/8808521a8a76216cd4890aec288775b8f95d2f3e/index.html#L67
https://github.com/mwhite192/GoMikeDesigns/blob/8808521a8a76216cd4890aec288775b8f95d2f3e/index.html#L85
https://github.com/mwhite192/GoMikeDesigns/blob/8808521a8a76216cd4890aec288775b8f95d2f3e/index.html#L125
https://github.com/mwhite192/GoMikeDesigns/blob/8808521a8a76216cd4890aec288775b8f95d2f3e/index.html#L154
https://github.com/mwhite192/GoMikeDesigns/blob/8808521a8a76216cd4890aec288775b8f95d2f3e/index.html#L160
https://github.com/mwhite192/GoMikeDesigns/blob/8808521a8a76216cd4890aec288775b8f95d2f3e/index.html#L169
https://github.com/mwhite192/GoMikeDesigns/blob/8808521a8a76216cd4890aec288775b8f95d2f3e/index.html#L180
https://github.com/mwhite192/GoMikeDesigns/blob/8808521a8a76216cd4890aec288775b8f95d2f3e/index.html#L189

**Comment by AccessiT3ch** [comment]
@mwhite192 - it looks like your favicon should have `type="image/webp"`, right? If that doesn't work then it might make sense to leave the favicon as a PNG.

**Comment by mwhite192** [comment]
@AccessiT3ch - you were correct.  I changed to `type="image/webp"` and the favicon did display.
